#!/bin/zsh

check_git_installed() {
    if ! command -v git &>/dev/null; then
        echo "git is not installed. Please install git before continuing."
        exit 1
    fi
}

check_cmake_installed() {
    if ! command -v cmake &>/dev/null; then
        echo "cmake is not installed. Please install cmake before continuing."
        exit 1
    fi
}

remove_juce_directory() {
    cd ~/Downloads || exit 1
    if [ -d "./JUCE" ]; then
        rm -rf "./JUCE"
    fi
}

# prepare
check_git_installed
check_cmake_installed
remove_juce_directory

# clone JUCE from github
cd ~/Downloads || exit 1
git clone https://github.com/juce-framework/JUCE.git

# prepare install configuration
cd JUCE || exit 1
cmake -B cmake-build-install -DCMAKE_INSTALL_PREFIX=/opt/local/libexec/JUCE

# install
sudo cmake --build cmake-build-install --target install

# cleanup
remove_juce_directory
cd ~
